name: Build and Release

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Docker image caching
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
      - name: Restore volume caching
        id: restore_cache
        uses: BYK/docker-volume-cache-action/restore@main
        with:
          key: docker-volumes-v1-state
          restore-keys: |
            docker-volumes-v1-
          volumes: |
            flatpak-builds
      - name: Build
        env:
          TODESK_DOMAIN: ${{ secrets.TODESK_DOMAIN }}
          TODESK_DIR: ${{ secrets.TODESK_DIR }}
        run: |
          ./docker.sh
      - name: Save volume caching
        if: steps.restore_cache.outputs.cache-hit != 'true'
        uses: BYK/docker-volume-cache-action/save@main
        with:
          key: ${{ steps.restore_cache.outputs.cache-primary-key }}
          volumes: |
            flatpak-builds
      - name: Set Release Version
        id: vars
        run: echo "VERSION=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./*/*.flatpak
          tag_name: ${{ steps.vars.outputs.VERSION }}
